create table if not exists public.beats (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text,
  bpm integer,
  key text,
  duration text,
  duration_seconds integer,
  preview_url text,
  cover_url text,
  price numeric(10, 2) default 29.99,
  tags text[] default '{}',
  description text,
  stems_available boolean default true,
  delivery_files jsonb not null default '[]'::jsonb,
  published boolean default false,
  sort_order integer default 100,
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text,
  excerpt text,
  body text[] default '{}',
  tags text[] default '{}',
  art text,
  tone text default 'yellow',
  read_time text default '4 MIN',
  featured boolean default false,
  published boolean default false,
  published_at timestamptz default now(),
  created_at timestamptz default now()
);

alter table public.posts
add column if not exists image_url text;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  customer_email text not null,
  customer_first_name text,
  customer_last_name text,
  items jsonb not null default '[]'::jsonb,
  contract_urls text[] not null default '{}',
  subtotal numeric(10, 2) not null default 0,
  discount jsonb not null default '{}'::jsonb,
  total numeric(10, 2) not null default 0,
  currency text not null default 'EUR',
  status text not null default 'demo',
  payment_provider text,
  payment_reference text,
  license_acceptance jsonb not null default '{}'::jsonb,
  email_sent_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (
    status in ('demo', 'pending_payment', 'paid', 'email_sent', 'delivered', 'cancelled', 'refunded')
  ),
  constraint orders_email_check check (position('@' in customer_email) > 1),
  constraint orders_total_check check (total >= 0),
  constraint orders_items_array_check check (jsonb_typeof(items) = 'array')
);

alter table public.orders
add column if not exists subtotal numeric(10, 2) not null default 0,
add column if not exists discount jsonb not null default '{}'::jsonb;

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  label text,
  discount_type text not null default 'percent',
  discount_value numeric(10, 2) not null,
  applies_to text not null default 'all',
  min_order_total numeric(10, 2) not null default 0,
  max_uses integer,
  used_count integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promo_codes_code_upper_check check (code = upper(code)),
  constraint promo_codes_discount_type_check check (discount_type in ('percent', 'fixed')),
  constraint promo_codes_applies_to_check check (applies_to in ('all', 'beats', 'services')),
  constraint promo_codes_discount_value_check check (discount_value > 0),
  constraint promo_codes_min_order_total_check check (min_order_total >= 0),
  constraint promo_codes_used_count_check check (used_count >= 0),
  constraint promo_codes_max_uses_check check (max_uses is null or max_uses > 0)
);

create index if not exists promo_codes_code_idx on public.promo_codes (code);
create index if not exists promo_codes_active_idx on public.promo_codes (active);

create table if not exists public.test_feedback (
  id uuid primary key default gen_random_uuid(),
  tester_name text,
  tester_email text,
  device text,
  ratings jsonb not null default '{}'::jsonb,
  clicked text,
  blocked text,
  unclear_step text,
  trust_notes text,
  bugs text,
  priority text,
  would_buy text,
  created_at timestamptz not null default now(),
  constraint test_feedback_email_check check (
    tester_email is null
    or tester_email = ''
    or position('@' in tester_email) > 1
  ),
  constraint test_feedback_would_buy_check check (
    would_buy is null
    or would_buy in ('yes', 'maybe', 'no')
  )
);

create index if not exists test_feedback_created_at_idx on public.test_feedback (created_at desc);

create table if not exists public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  source text not null default 'footer',
  status text not null default 'subscribed',
  page_url text,
  user_agent text,
  subscribed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint newsletter_subscribers_email_check check (
    email = lower(email)
    and position('@' in email) > 1
    and position('.' in split_part(email, '@', 2)) > 1
  ),
  constraint newsletter_subscribers_status_check check (
    status in ('subscribed', 'unsubscribed')
  )
);

create index if not exists newsletter_subscribers_created_at_idx
on public.newsletter_subscribers (subscribed_at desc);

alter table public.test_feedback alter column tester_name drop not null;
alter table public.test_feedback alter column tester_email drop not null;
alter table public.test_feedback alter column device drop not null;
alter table public.test_feedback alter column clicked drop not null;
alter table public.test_feedback alter column blocked drop not null;
alter table public.test_feedback alter column unclear_step drop not null;
alter table public.test_feedback alter column trust_notes drop not null;
alter table public.test_feedback alter column bugs drop not null;
alter table public.test_feedback alter column priority drop not null;
alter table public.test_feedback alter column would_buy drop not null;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
    and table_name = 'test_feedback'
    and column_name = 'title'
  ) then
    alter table public.test_feedback alter column title drop not null;
  end if;
end $$;

grant insert on public.test_feedback to anon;
grant insert on public.test_feedback to authenticated;
grant select, update, delete on public.test_feedback to authenticated;
grant insert on public.newsletter_subscribers to anon;
grant insert on public.newsletter_subscribers to authenticated;
grant select, update, delete on public.newsletter_subscribers to authenticated;

create index if not exists orders_customer_email_idx on public.orders (customer_email);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.beats enable row level security;
alter table public.posts enable row level security;
alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.orders enable row level security;
alter table public.promo_codes enable row level security;
alter table public.test_feedback enable row level security;
alter table public.newsletter_subscribers enable row level security;

drop policy if exists "Published beats are readable" on public.beats;
create policy "Published beats are readable"
on public.beats for select
using (
  published = true
  or exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin beats write access" on public.beats;
create policy "Admin beats write access"
on public.beats for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Published posts are readable" on public.posts;
create policy "Published posts are readable"
on public.posts for select
using (
  published = true
  or exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin posts write access" on public.posts;
create policy "Admin posts write access"
on public.posts for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admins can read admin list" on public.admin_users;
create policy "Admins can read admin list"
on public.admin_users for select
using (user_id = auth.uid());

drop policy if exists "Public site settings are readable" on public.site_settings;
create policy "Public site settings are readable"
on public.site_settings for select
using (true);

drop policy if exists "Admin site settings write access" on public.site_settings;
create policy "Admin site settings write access"
on public.site_settings for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

insert into public.site_settings (key, value)
values (
  'ticker',
  '{"tickerText":"MP3 / WAV / STEMS INSTANT DELIVERY | NEW DROP: SHADOW OF THE SP | REAL SAMPLES. RAW SOUL. TIMELESS BANGERS. SP-1200 MPC3000 LICENSING OPTIONS BUILT FOR ARTISTS"}'::jsonb
)
on conflict (key) do nothing;

drop policy if exists "Public can create demo orders" on public.orders;

drop policy if exists "Admin orders access" on public.orders;
create policy "Admin orders access"
on public.orders for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Customers can read their own orders" on public.orders;
create policy "Customers can read their own orders"
on public.orders for select
using (lower(customer_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "Admin promo codes access" on public.promo_codes;
create policy "Admin promo codes access"
on public.promo_codes for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop trigger if exists set_promo_codes_updated_at on public.promo_codes;
create trigger set_promo_codes_updated_at
before update on public.promo_codes
for each row execute function public.set_updated_at();

drop policy if exists "Public can create test feedback" on public.test_feedback;
create policy "Public can create test feedback"
on public.test_feedback for insert
with check (jsonb_typeof(ratings) = 'object');

drop policy if exists "Admin test feedback access" on public.test_feedback;
create policy "Admin test feedback access"
on public.test_feedback for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Public can subscribe to newsletter" on public.newsletter_subscribers;
create policy "Public can subscribe to newsletter"
on public.newsletter_subscribers for insert
with check (
  status = 'subscribed'
  and email = lower(email)
  and position('@' in email) > 1
);

drop policy if exists "Admin newsletter subscribers access" on public.newsletter_subscribers;
create policy "Admin newsletter subscribers access"
on public.newsletter_subscribers for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('covers', 'covers', true), ('previews', 'previews', true), ('blog-images', 'blog-images', true), ('contracts', 'contracts', false), ('deliverables', 'deliverables', false)
on conflict (id) do nothing;

drop policy if exists "Public covers are readable" on storage.objects;
create policy "Public covers are readable"
on storage.objects for select
using (bucket_id = 'covers');

drop policy if exists "Public previews are readable" on storage.objects;
create policy "Public previews are readable"
on storage.objects for select
using (bucket_id = 'previews');

drop policy if exists "Public blog images are readable" on storage.objects;
create policy "Public blog images are readable"
on storage.objects for select
using (bucket_id = 'blog-images');

drop policy if exists "Admin can upload covers" on storage.objects;
create policy "Admin can upload covers"
on storage.objects for insert
with check (
  bucket_id = 'covers'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin can upload previews" on storage.objects;
create policy "Admin can upload previews"
on storage.objects for insert
with check (
  bucket_id = 'previews'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin can upload blog images" on storage.objects;
create policy "Admin can upload blog images"
on storage.objects for insert
with check (
  bucket_id = 'blog-images'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin can upload deliverables" on storage.objects;
create policy "Admin can upload deliverables"
on storage.objects for insert
with check (
  bucket_id = 'deliverables'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);
