create table if not exists public.beats (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text,
  bpm integer,
  key text,
  duration text,
  duration_seconds integer,
  preview_url text,
  cover_url text,
  price numeric(10, 2) default 29.99,
  tags text[] default '{}',
  description text,
  published boolean default false,
  sort_order integer default 100,
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text,
  excerpt text,
  body text[] default '{}',
  tags text[] default '{}',
  art text,
  tone text default 'yellow',
  read_time text default '4 MIN',
  featured boolean default false,
  published boolean default false,
  published_at timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

alter table public.beats enable row level security;
alter table public.posts enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Published beats are readable" on public.beats;
create policy "Published beats are readable"
on public.beats for select
using (
  published = true
  or exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin beats write access" on public.beats;
create policy "Admin beats write access"
on public.beats for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Published posts are readable" on public.posts;
create policy "Published posts are readable"
on public.posts for select
using (
  published = true
  or exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin posts write access" on public.posts;
create policy "Admin posts write access"
on public.posts for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admins can read admin list" on public.admin_users;
create policy "Admins can read admin list"
on public.admin_users for select
using (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('covers', 'covers', true), ('previews', 'previews', true)
on conflict (id) do nothing;

drop policy if exists "Public covers are readable" on storage.objects;
create policy "Public covers are readable"
on storage.objects for select
using (bucket_id = 'covers');

drop policy if exists "Public previews are readable" on storage.objects;
create policy "Public previews are readable"
on storage.objects for select
using (bucket_id = 'previews');

drop policy if exists "Admin can upload covers" on storage.objects;
create policy "Admin can upload covers"
on storage.objects for insert
with check (
  bucket_id = 'covers'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin can upload previews" on storage.objects;
create policy "Admin can upload previews"
on storage.objects for insert
with check (
  bucket_id = 'previews'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);
