create table if not exists public.beats (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text,
  bpm integer,
  key text,
  duration text,
  duration_seconds integer,
  preview_url text,
  cover_url text,
  price numeric(10, 2) default 29.99,
  tags text[] default '{}',
  description text,
  published boolean default false,
  sort_order integer default 100,
  created_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text,
  excerpt text,
  body text[] default '{}',
  tags text[] default '{}',
  art text,
  tone text default 'yellow',
  read_time text default '4 MIN',
  featured boolean default false,
  published boolean default false,
  published_at timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  customer_email text not null,
  customer_first_name text,
  customer_last_name text,
  items jsonb not null default '[]'::jsonb,
  contract_urls text[] not null default '{}',
  total numeric(10, 2) not null default 0,
  currency text not null default 'EUR',
  status text not null default 'demo',
  payment_provider text,
  payment_reference text,
  license_acceptance jsonb not null default '{}'::jsonb,
  email_sent_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (
    status in ('demo', 'pending_payment', 'paid', 'email_sent', 'delivered', 'cancelled', 'refunded')
  ),
  constraint orders_email_check check (position('@' in customer_email) > 1),
  constraint orders_total_check check (total >= 0),
  constraint orders_items_array_check check (jsonb_typeof(items) = 'array')
);

create table if not exists public.test_feedback (
  id uuid primary key default gen_random_uuid(),
  tester_name text,
  tester_email text,
  device text,
  ratings jsonb not null default '{}'::jsonb,
  clicked text,
  blocked text,
  unclear_step text,
  trust_notes text,
  bugs text,
  priority text,
  would_buy text,
  created_at timestamptz not null default now(),
  constraint test_feedback_email_check check (
    tester_email is null
    or tester_email = ''
    or position('@' in tester_email) > 1
  ),
  constraint test_feedback_would_buy_check check (
    would_buy is null
    or would_buy in ('yes', 'maybe', 'no')
  )
);

create index if not exists test_feedback_created_at_idx on public.test_feedback (created_at desc);

create index if not exists orders_customer_email_idx on public.orders (customer_email);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.beats enable row level security;
alter table public.posts enable row level security;
alter table public.admin_users enable row level security;
alter table public.orders enable row level security;
alter table public.test_feedback enable row level security;

drop policy if exists "Published beats are readable" on public.beats;
create policy "Published beats are readable"
on public.beats for select
using (
  published = true
  or exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin beats write access" on public.beats;
create policy "Admin beats write access"
on public.beats for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Published posts are readable" on public.posts;
create policy "Published posts are readable"
on public.posts for select
using (
  published = true
  or exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin posts write access" on public.posts;
create policy "Admin posts write access"
on public.posts for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admins can read admin list" on public.admin_users;
create policy "Admins can read admin list"
on public.admin_users for select
using (user_id = auth.uid());

drop policy if exists "Public can create demo orders" on public.orders;
create policy "Public can create demo orders"
on public.orders for insert
with check (
  status = 'demo'
  and customer_email is not null
  and jsonb_array_length(items) > 0
);

drop policy if exists "Admin orders access" on public.orders;
create policy "Admin orders access"
on public.orders for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Public can create test feedback" on public.test_feedback;
create policy "Public can create test feedback"
on public.test_feedback for insert
with check (jsonb_typeof(ratings) = 'object');

drop policy if exists "Admin test feedback access" on public.test_feedback;
create policy "Admin test feedback access"
on public.test_feedback for all
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('covers', 'covers', true), ('previews', 'previews', true), ('contracts', 'contracts', false)
on conflict (id) do nothing;

drop policy if exists "Public covers are readable" on storage.objects;
create policy "Public covers are readable"
on storage.objects for select
using (bucket_id = 'covers');

drop policy if exists "Public previews are readable" on storage.objects;
create policy "Public previews are readable"
on storage.objects for select
using (bucket_id = 'previews');

drop policy if exists "Admin can upload covers" on storage.objects;
create policy "Admin can upload covers"
on storage.objects for insert
with check (
  bucket_id = 'covers'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Admin can upload previews" on storage.objects;
create policy "Admin can upload previews"
on storage.objects for insert
with check (
  bucket_id = 'previews'
  and exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);
